In [3]:
import numpy as np

# Crear Arreglos desde Listas de Python

Podemos crear un arreglo mediante la conversión directa de una lista o lista de listas:

In [7]:
my_list = [1,2,3] #lista en python
type(my_list)


list

In [10]:
np.array(my_list) #conversion de una lista a arreglo mediante el metodo 'array'


array([1, 2, 3])

In [17]:
a = np.array(my_list) #se peude asignar a una variable
type(a) #tipo de dato
a.ndim
a.shape

(3,)

In [1]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]] # Una lista de listas
my_matrix
type(my_matrix)

list

In [6]:
my_matrix=np.array(my_matrix) # conversion de una lista de listas a Matriz
type(my_matrix)

numpy.ndarray

In [9]:
b = np.array(my_matrix) # aasginar la conversion a una variable
type(b) # tipo de dato
b.shape #dimensiones de la matriz



(3, 3)

# Metodos integrados (Built-in Methods)

Existen muchas funciones para de generar arreglos
arange

Devuelve valores espaciados uniformemente dentro de un intervalo dado. Es muy parecida a la funcion range de las basicas de python.

In [22]:

# generar un arreglo de enteros desde 0 hasta 9, recordar que el valor final no se incluye
np.arange(1,10,2)  # arange(valor_inicial,valor_final-1)


array([1, 3, 5, 7, 9])

In [ ]:
np.arange(0,11,2) ## arange(valor_inicial,valor_final-1,paso)


# zeros y ones

Generar arreglos de Ceros o Unos

In [31]:
z=np.zeros(10) # Generar un arreglo de ceros que contenga 3 elementos
print(z)
z

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.zeros((5,5)) # Generar una matriz de ceros de 5 x 5 elementos


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3) # Generar un arreglo de unos que contenga 3 elementos


array([1., 1., 1.])

In [11]:
np.ones((3,7)) # Generar una matriz de unos de 5 x 5 elementos


array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [38]:
np.zeros((5))+2

array([2., 2., 2., 2., 2.])

# linspace

Devuelve números espaciados uniformemente durante un intervalo especificado.

In [42]:
# Generar 3 valores iniciando en 0 y terminando en 10 (incluyendolo)
np.linspace(-5,5,50) # linspace(valor_inicial, valor_final, numero_de_elementos)


array([-5.        , -4.79591837, -4.59183673, -4.3877551 , -4.18367347,
       -3.97959184, -3.7755102 , -3.57142857, -3.36734694, -3.16326531,
       -2.95918367, -2.75510204, -2.55102041, -2.34693878, -2.14285714,
       -1.93877551, -1.73469388, -1.53061224, -1.32653061, -1.12244898,
       -0.91836735, -0.71428571, -0.51020408, -0.30612245, -0.10204082,
        0.10204082,  0.30612245,  0.51020408,  0.71428571,  0.91836735,
        1.12244898,  1.32653061,  1.53061224,  1.73469388,  1.93877551,
        2.14285714,  2.34693878,  2.55102041,  2.75510204,  2.95918367,
        3.16326531,  3.36734694,  3.57142857,  3.7755102 ,  3.97959184,
        4.18367347,  4.3877551 ,  4.59183673,  4.79591837,  5.        ])

In [53]:
# Generar 50 valores iniciando en 0 y terminando en 10 (incluyendolo)
np.linspace(0,10000,50)



array([    0.        ,   204.08163265,   408.16326531,   612.24489796,
         816.32653061,  1020.40816327,  1224.48979592,  1428.57142857,
        1632.65306122,  1836.73469388,  2040.81632653,  2244.89795918,
        2448.97959184,  2653.06122449,  2857.14285714,  3061.2244898 ,
        3265.30612245,  3469.3877551 ,  3673.46938776,  3877.55102041,
        4081.63265306,  4285.71428571,  4489.79591837,  4693.87755102,
        4897.95918367,  5102.04081633,  5306.12244898,  5510.20408163,
        5714.28571429,  5918.36734694,  6122.44897959,  6326.53061224,
        6530.6122449 ,  6734.69387755,  6938.7755102 ,  7142.85714286,
        7346.93877551,  7551.02040816,  7755.10204082,  7959.18367347,
        8163.26530612,  8367.34693878,  8571.42857143,  8775.51020408,
        8979.59183673,  9183.67346939,  9387.75510204,  9591.83673469,
        9795.91836735, 10000.        ])

# eye

Crea la matriz identidad

In [12]:
np.eye(6) # crea la matriz identidad de 4x4 elementos


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Numeros Aleatorios (Random)

Numpy tiene diferentes formas de crear arrelgos de numeros aleatorios, el modulo para realizar esto se llama Random:
rand

Crea un arreglo de la forma dada y rellenela con muestras aleatorias de una distribución uniforme sobre [0, 1).

In [98]:
# creacion de un arreglo de 2 elementos 1 una dimension
np.random.rand(10) #Los numeros aleatorios seran de una distribucion uniforme


array([0.80079698, 0.23122978, 0.04188611, 0.15157627, 0.91446273,
       0.74425972, 0.65020402, 0.05268119, 0.06471175, 0.61319261])

In [102]:
# creacion de un arreglo de 5x5
np.random.rand(5,5) #Los numeros aleatorios seran de una distribucion uniforme


array([[0.11713819, 0.68681658, 0.96243942, 0.58162323, 0.22176115],
       [0.14146205, 0.56967551, 0.68016591, 0.48398685, 0.3327137 ],
       [0.28077886, 0.02283199, 0.79039679, 0.1180267 , 0.42133245],
       [0.34587695, 0.70409654, 0.66804073, 0.11976572, 0.17188536],
       [0.97483861, 0.85109473, 0.39141791, 0.62129547, 0.61898447]])

# randn

Devuelve una muestra (o muestras) de la distribución “estándar normal”. A diferencia del rand que es uniforme:

In [103]:
# creacion de un arreglo de 2 elementos 1 una dimension
np.random.randn(2) #Los numeros aleatorios seran de una distribucion "estándar normal"


array([ 0.59745813, -1.16604351])

In [ ]:
# creacion de un arreglo de 5x5
np.random.randn(5,5) #Los numeros aleatorios seran de una distribucion "estándar normal"


# randint

Entrega numeros enteros aleatorios desde inicio (inclusivo) hasta final (exclusivo).

In [116]:
np.random.randint(1,101) # Genera un numero aleatorio entre 1 y 99


88

In [13]:
np.random.randint(1,101,(5)) # Genera un arreglo de 10 elementos entre 1 y 99


array([74, 48, 53, 19, 46])

 
 
 # Atributos y Metodos de los arreglos

In [168]:
import numpy as np
arr = np.arange(24) #Genera un arreglo de numeros enteros del 0 al 24
ranarr = np.random.randint(0,25,10) #Genera un arreglo de 10 elementosdel 0 al 49


In [169]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [164]:
ranarr


array([ 4, 21,  2, 15, 18, 19,  7,  9, 14,  8])

# Reshape

Devuelve una matriz que contiene los mismos datos con una nueva distribucion

In [172]:
# arr es un vector de 25 elementos y se convertira en una matriz de 5x5
arr.reshape(4,6)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

# max,min,argmax,argmin

Estos son métodos útiles para encontrar valores máximos o mínimos. O para encontrar el indice de su ubicacione usando argmin o argmax

In [173]:
ranarr


array([20, 19, 12, 23,  3,  5, 10,  2,  6, 12])

In [174]:
ranarr.max() # Valor maximo del arreglo


23

In [175]:
ranarr.argmax() # Posicion del valor maximo del arreglo (recordar que empieza en cero)


3

In [176]:
ranarr.min() # Valor minimo del arreglo


2

In [177]:
ranarr.argmin() # Posicion del valor maximo del arreglo (recordar que empieza en cero)


7

# Shape

Shape es un attribute que los arreglos tienen para definir sus dimensiones (No es metodo):

In [179]:
# Vector
arr.shape


(24,)

In [181]:
# Cambiando las dimensiones del arreglo para que sea una matriz
# de una sola dimension horizontal
arr.reshape(4,6)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [182]:
# Cambiando las dimensiones del arreglo para que sea una matriz
# de una sola dimension vertical
arr.reshape(24,1)


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [183]:
arr.reshape(24,1).shape


(24, 1)

# size

Numero de elementos en un arreglo

In [17]:
arr_1d = np.array([1,2,3,4,5,6,7,8,9,10])
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45],[50,55,60]))
arr_2d.size

12

In [18]:
len(arr_2d) # Numero de elementos de la matriz

4

# ndim

Numero de dimensiones del arreglo o matriz

In [19]:
arr_2d.ndim


2

In [191]:
arr_1d.ndim

1

# Indexacion y Seleccion en NumPy

Como indexar y seleccionar elementos o grupos de elementos de un arreglo (array)

In [199]:
#Creando un arreglo de ejemplo
arr = np.random.randint(0,101,(10)) # Generar un arreglo de enteros del 0 hasta el 10
arr


array([38, 82, 62,  4, 65, 70, 80,  0, 47, 30])

In [200]:
arr.dtype # tipos de datos dentro del arreglo


dtype('int32')

# Indexación y Selección con corchetes

La forma más sencilla de elegir uno o algunos elementos de una matriz es similar a las listas de Python:

In [201]:
# Obtener un valor conociendo su indice (index)
arr[8]


47

In [203]:
#Obtener los valores en un rango [valor_inicial, valor_final -1]
arr[1:6]


array([82, 62,  4, 65, 70])

In [208]:
#Obtener los valores en un rango [valor_inicial, valor_final -1]
arr[1:5:2]


array([82,  4])

# Broadcasting (Difusion)

Los arreglos de Numpy difieren de una lista normal de Python en su capacidad de Broadcasting, qeu es asignar un valor a un rango de posiciones:

In [209]:
# definiendo un valor para todo un rango de posiciones (Broadcasting)
arr[1:5]=100 # Asignar el numero 100 a las pocisiones desde el 0 hasta el 4
arr


array([ 38, 100, 100, 100, 100,  70,  80,   0,  47,  30])

In [215]:
#crear nuevamente el arreglo con el que estabamos trabajando
arr = np.arange(0,11)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [216]:
#NOTA importante en la seleccion de rangos (sclicing)
# los arreglos son mutables
slice_of_arr = arr[2:6]
slice_of_arr


array([2, 3, 4, 5])

In [217]:
#Cambiar todos los valores a 99
slice_of_arr[:]=99
slice_of_arr


array([99, 99, 99, 99])

Observe que los cambios tambien ocurren en el arreglo original

In [218]:
arr


array([ 0,  1, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Los datos no se copian, ¡es un puntero a el arreglo original! ¡Esto evita problemas de memoria!

In [219]:
# Para obtener una copia, se debe hacer explicito
arr = np.arange(0,11)
arr_copy = arr.copy()
arr_copy[:] = 99
arr_copy


array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [220]:
# Observe que el arreglo original no se modifico
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Indexacion de arreglos 2D (matrices)

El formato general es arr_2d[fila][col] o arr_2d[fila,col]. Se recomienda usar la notacion con la coma por claridad.#

In [20]:
# Creacion de una matriz de 3x3
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45],[33,77,55],))
arr_2d  


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [33, 77, 55]])

In [22]:
#Indexando por filas
arr_2d[0] # Obtener la fila 1 (recordar que el indice de python empieza en 0)


array([ 5, 10, 15])

In [25]:
# El formato es **arr_2d[fila][col]** o **arr_2d[fila,col]**
# Obteniendo un elemento en especifico
arr_2d[2][1] # elemento de la fila 1 columna 0


40

In [33]:
# seleccion de rangos en arreglos 2D (slicing)
print(arr_2d)   
print("----------------------------------------------------------------")
#dimensiones (2,2) desde la esquina superior derecha
print(arr_2d[2:,:2]) # filas [0,1] y columnas 1 hasta el final


[[ 5 10 15]
 [20 25 30]
 [35 40 45]
 [33 77 55]]
----------------------------------------------------------------
[[35 40]
 [33 77]]


In [36]:
# fila de indice 2
vector_matriz=arr_2d[2]
print(vector_matriz)


[35 40 45]


In [38]:
# todos los elementos de las columnas que estan en la fila de posicion 2
arr_2d[2,:2]


array([35, 40])

# Indexacion especial

La indexación especial permite seleccionar filas o columnas enteras desordenadas

In [39]:
#Creando una matriz de zeros
arr2d = np.zeros((10,5))
arr2d


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
#Tamaño del arreglo
print(arr2d[0])
print(arr2d[0].shape)
print(arr2d.shape)
filas = arr2d.shape[0]
filas


[0. 0. 0. 0. 0.]
(5,)
(10, 5)


10

In [51]:
# Creando una matriz con elementos que contienen el valor correspondiente a la posicion de la fila
#i =0 hasta i=10-1=9
for i in range(filas):
    arr2d[i] = i
    
arr2d


array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9.]])

La indexacion especial permite:

In [54]:
# sacar las filas 2, 4 , 6, 8
subMatriz=arr2d[[2,4,6,8]] # observe el uso de los dobles corchetes
print(subMatriz)

[[2. 2. 2. 2. 2.]
 [4. 4. 4. 4. 4.]
 [6. 6. 6. 6. 6.]
 [8. 8. 8. 8. 8.]]


In [55]:
#Permite cualquier orden
arr2d[[6,4,2,7]]


array([[6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7.]])

# Ayudas para indexacion

La indexación de una matriz 2d puede ser un poco confusa al principio, especialmente cuando comienza a agregar pasos en la seleccion. Pruebe buscar imagenes en google con la parala NumPy indexing y encontrara ejemplos utiles como: 

![Alt text](af0031e07738e01a1dd4413c08f08e3f.png)

# Seleccion basados en operadores de comparacion

In [ ]:
# creacion de un arreglo de enteros desde 0 hasta 10
arr = np.arange(1,11) # recordar que el ultimo valor no se incluye
arr


In [ ]:
arr > 4 # determinar cuales valores del arreglo son mayores que 4
# el resultado es un arreglo de Booleans


In [138]:
bool_arr = arr>4 # creacion de arreglo de booleans


In [ ]:
bool_arr


In [ ]:
# Seleccion de elementos usando un arreglo de Booleans
arr[bool_arr] # Solamente se retornan los elementos en los cuales las posiciones de bool_arr sean verdaderas


In [ ]:
# Se puede hacer esta seleccion mucho mas rapida realizando la comparacion dentro de los corchetes
arr[arr>5] # Obtener los valores del arreglo mayores que 2


In [ ]:
x = 2 # se puede hacer usando una variable
arr[arr>x]


In [ ]:
x = 2 # se puede hacer usando una variable
arr[arr>x]


In [74]:
import numpy as np

# Crear una matriz aleatoria de 3x3 para mostrar un ejemplo
matriz_aleatoria = np.random.randint(0, 100,(5,5))
matriz_aleatoria


array([[88, 42, 68, 47, 32],
       [93, 78, 82, 31, 37],
       [16, 41, 40, 40, 35],
       [51, 98,  2, 91, 75],
       [34, 67, 76, 50, 42]])

In [69]:
seleccion_mayores=matriz_aleatoria[matriz_aleatoria>50]
print(seleccion_mayores)

[81 92 91 74 59 84 69 69 89 97 70 70 67 65 67]


In [75]:
igual_a_50=matriz_aleatoria[matriz_aleatoria==50]
print(igual_a_50)

[50]


In [77]:
matriz_rango=matriz_aleatoria[(matriz_aleatoria>50) & (matriz_aleatoria<70)]
print(matriz_rango)

[68 51 67]


In [79]:
matriz_aleatoria[matriz_aleatoria>50]=0
print(matriz_aleatoria)

[[ 0 42  0 47 32]
 [ 0  0  0 31 37]
 [16 41 40 40 35]
 [ 0  0  2  0  0]
 [34  0  0 50 42]]


# Concatenacion

In [81]:
# En una dimension
x = np.array([1, 2, 3]) # Vector de valores
y = np.array([3, 2, 1]) # Vector de valores
z=np.concatenate([x, y]) # Concatenacion
z


array([1, 2, 3, 3, 2, 1])

In [83]:
# En dos dimensiones de forma vertical
grid = np.array([[1, 2, 3],[4, 5, 6]])
print(grid)
print("----------------------------------------")
grid2=np.concatenate([grid, grid])
print(grid2)


[[1 2 3]
 [4 5 6]]
----------------------------------------
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [ ]:
# En dos dimensiones de forma vertical
grid = np.array([[1, 2, 3],[4, 5, 6]])
np.concatenate([grid, grid])


In [84]:
# En dos dimensiones de forma horizontal
grid = np.array([[1, 2, 3],[4, 5, 6]])
np.concatenate([grid, grid],axis=1)


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Operaciones con NumPy

Con las listas de python no se pueden realizar operaciones elemento a elemento, pero con NumPy si se puede realizar.

## Como es el comportamiento de las listas ante las siguientres operaciones:

In [225]:
# observar el comportamiento de las listas
lista = list(range(11))
lista


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [226]:
lista + lista # este procedimento lo que hace es concatenar las listas


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [228]:
x = 2
lista*2 # este procedimento hace que se repita la lista x numero de veces


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Aritmetica

Puede realizar fácilmente aritmética de matriz a matriz o aritmética de escalar con matriz.

In [229]:
import numpy as np # importar la libreria de NumPy
arr = np.arange(0,10) # crear un arreglo de 10 elementos
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [230]:
arr + arr # Suma elemento a elemento de los arreglos


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [233]:
# Suma de valores uno a uno con arreglos
aa = np.arange(5)
bb = np.arange(10) # este arreglo es mas grande que el anterios
aa+bb[:5] # deben tener el mismo tamaño para realizar la suma


array([0, 2, 4, 6, 8])

In [235]:
arr * arr # Multiplicacion elemento a elemento


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [239]:
arr - 5 # Resta elemento a elemento


array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [241]:
# Mensaje de advertencia si se presenta una division por cero, pero no hay error!
# solo se reemplazo por el valor nan
print(arr)
arr/arr # division elemento a elemento


[0 1 2 3 4 5 6 7 8 9]


C:\Users\Berserk\AppData\Local\Temp\ipykernel_17724\1436408975.py:4: RuntimeWarning: invalid value encountered in divide
  arr/arr # division elemento a elemento


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [244]:
arr**3 # eleva al cubo cada elemento del arreglo


array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

# Funciones Universales de los arreglos

NumPy tiene integrado muchas funciones universales, que son esencialmente solo operaciones matemáticas que se pueden usar para realizar la operación en todo el arreglo. Las mas importantes son:

    Matematicas
    Trigonometria
    Funciones de comparacion
    Funciones de punto flotante


In [249]:
#Calcular la raiz cuadrada de cada elemento
np.sqrt(124)


11.135528725660043

In [252]:
#Calcular el exponencial (e^) de cada elemento
np.exp(arr)


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [256]:
# Obtener el valor maximo como una funcion
print(arr)
np.mean(arr) #lo mismo arr.max()


[0 1 2 3 4 5 6 7 8 9]


4.5

In [259]:
# Calcular el Sin de cada elemento
np.sin(arr)


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [260]:
# Calcular el Logaritmo de cada elemento
np.log(arr)


C:\Users\Berserk\AppData\Local\Temp\ipykernel_17724\1673722079.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [261]:
# Calcular el valor absoluto
np.abs(arr)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Estadistica

In [264]:
# Desviacion estandar
print(arr)
np.std(arr)


[0 1 2 3 4 5 6 7 8 9]


2.8722813232690143

In [265]:
# Promedio de los valores
np.mean(arr) 


4.5

In [266]:
# Media
np.median(arr)


4.5

In [267]:
# Varianza
np.var(arr)


8.25

# Operaciones de Matrices

In [85]:
#creacion de una matriz de ejemplo
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [86]:
# transpuesta de una matriz
arr_2d.T # tambien puede ser arr_2d.transpose()


array([[ 5, 20, 35],
       [10, 25, 40],
       [15, 30, 45]])

In [95]:
# Multiplicacion de matrices
a = np.array([[1,4,3],[4,3,1]]) # vector = arreglo de 1 dimension
b = np.array([[2,-1,5],[0,2,5]]) # vector = arreglo de 1 dimension
np.dot(a,b.T) # producto punto


array([[13, 23],
       [10, 11]])

In [91]:
matriz_a=np.random.randint(0,100,(5,5))
matriz_b=np.random.randint(0,100,(5,5))
print(matriz_a)
print("----------------------------------------")
print(matriz_b)

[[48 41 99 18 30]
 [37 38 49 19 51]
 [51 21 53 67 89]
 [24 13 69 55 72]
 [40  1 65 31  3]]
----------------------------------------
[[34 64 25 70 33]
 [64 32 38 36 25]
 [88 68 84 93 44]
 [28 81 10 87 12]
 [52 81  6 78 71]]


In [94]:
producto_punto=np.dot(matriz_a,matriz_b)
print(producto_punto)

[[15032 15004 11434 17949  9311]
 [11186 12586  6981 14146  8176]
 [14246 20176  7729 22026 11663]
 [13004 16931  7872 18966  9925]
 [ 8168  9766  6826 11812  4790]]


In [96]:
#Tambien puede ser de esta forma
matriz_a@matriz_b


array([[15032, 15004, 11434, 17949,  9311],
       [11186, 12586,  6981, 14146,  8176],
       [14246, 20176,  7729, 22026, 11663],
       [13004, 16931,  7872, 18966,  9925],
       [ 8168,  9766,  6826, 11812,  4790]])

In [ ]:
# Producto Cruz
a = np.array([1,4,3]) # vector = arreglo de 1 dimension
b = np.array([2,-1,5]) # vector = arreglo de 1 dimensi
np.cross(a,b)


In [ ]:
producto_cruz=np.cross(matriz_a,matriz_b)
print(producto_cruz)    

ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [100]:
import numpy as np

# Definir dos matrices donde cada fila representa un vector en 3D
matriz_a = np.array([[1, 4, 3],
                     [4, 3, 1],
                     [0, 2, 5]])

matriz_b = np.array([[2, -1, 5],
                     [1, 0, 3],
                     [3, 4, 2]])

# Calcular el producto cruz fila por fila
producto_cruz = np.cross(matriz_a, matriz_b)

print("Producto cruz de las matrices a y b, fila por fila:")
print(producto_cruz)


Producto cruz de las matrices a y b, fila por fila:
[[ 23   1  -9]
 [  9 -11  -3]
 [-16  15  -6]]


Ejercicio: Operaciones con Vectores

    Crear dos vectores aleatorios
        Usa NumPy para crear dos vectores de tamaño 5, cada uno con valores aleatorios entre 0 y 10.

    Realizar operaciones básicas
        Calcula la suma, resta, multiplicación y división de los dos vectores creados.

    Calcular la magnitud
        Calcula la magnitud (norma) de cada vector.

    Producto escalar
        Calcula el producto escalar de los dos vectores.

    Ángulo entre los vectores
        Calcula el ángulo (en grados) entre los dos vectores.

In [302]:
import numpy as np

vector_a = np.random.randint(0,10,5)
vector_b = np.random.randint(0,10,5)
print("Vector A: ",vector_a)
print("Vector B: ",vector_b)

Vector A:  [2 8 2 6 7]
Vector B:  [0 8 8 7 0]


In [304]:
suma = vector_a + vector_b
resta = vector_a - vector_b
multiplicacion = vector_a * vector_b
#division = vector_a / vector_b
div =np.divide(vector_a,vector_b, out=np.zeros_like(vector_a, dtype=float), where=vector_b!=0)

print("Suma: ",suma)
print("Resta: ",resta)
print("Multiplicacion: ",multiplicacion)
#print("Division: ",division)
print("Division pro: ",div)

Suma:  [ 2 16 10 13  7]
Resta:  [ 2  0 -6 -1  7]
Multiplicacion:  [ 0 64 16 42  0]
Division pro:  [0.         1.         0.25       0.85714286 0.        ]


In [305]:
magnitud_a = np.linalg.norm(vector_a)
magnitud_b = np.linalg.norm(vector_b)
print("Magnitud de A: ",magnitud_a)
print("Magnitud de B: ",magnitud_b)

Magnitud de A:  12.529964086141668
Magnitud de B:  13.30413469565007


In [309]:
productor_escalar = np.dot(vector_a,vector_b) #producto punto
print("Producto escalar: ",productor_escalar)
pp=vector_a@vector_b
print("Producto escalar: ",pp)

Producto escalar:  122
Producto escalar:  122


In [313]:
if magnitud_a * magnitud_b != 0:
    cos_angulo = productor_escalar/(magnitud_a*magnitud_b)
else:
    cos_angulo = 0
    
angulo =np.degrees(np.arccos(np.clip(cos_angulo, -1.0, 1.0)))

print("angulo entre A y B: ",angulo,"°")

angulo entre A y B:  42.958105534323884 °


# Ejercicios con matrices

### Ejercicio 1: Crear una matriz identidad

Descripción: Crea una matriz identidad de tamaño 4x4 y muestra el resultado.

### Ejercicio 2: Sumar dos matrices

Descripción: Crea dos matrices de tamaño 3x3 con números enteros aleatorios entre 0 y 10. Luego, realiza la suma de ambas matrices y muestra el resultado.

### Ejercicio 3: Multiplicar una matriz por un escalar

Descripción: Crea una matriz de tamaño 3x3 con números enteros aleatorios entre 1 y 5. Luego, multiplica todos sus elementos por un escalar, por ejemplo, 3.


### Ejercicio 4: Calcular el determinante de una matriz

Descripción: Crea una matriz de tamaño 2x2 con números enteros aleatorios entre 1 y 10 y calcula su determinante.usar np.linalg.det

### Ejercicio 5: Transponer una matriz

Descripción: Crea una matriz de tamaño 3x2 con números enteros aleatorios entre 0 y 9. Luego, calcula y muestra la transpuesta de la matriz.


In [3]:
import numpy as np
#ejercicio 1

def ejercicio1():
    matriz_identidad = np.eye(4)
    print(matriz_identidad)
    
#ejercicio 2   
def ejercicio2():
    matriz_a = np.random.randint(0,11,(3,3))
    matriz_b = np.random.randint(0,11,(3,3))
    suma = matriz_a + matriz_b
    print("Matriz A: \n",matriz_a)
    print("Matriz B: \n",matriz_b)
    print("Suma: \n",suma)
    
def ejercicio3():
    matriz_a = np.random.randint(0,6,(3,3))
    escalar = 3
    multiplicacion = matriz_a * escalar
    print("Matriz A: \n",matriz_a)
    print("Escalar: ",escalar)
    print("Multiplicacion: \n",multiplicacion)
    
def ejercicio4():
    matriz_a = np.random.randint(0,11,(2,2))
    det = np.linalg.det(matriz_a)
    print("Matriz A: \n",matriz_a)
    print("Determinante: ",det)
    
    
def ejercicio5():
    matriz_a = np.random.randint(0,10,(3,2))
    transpuesta = matriz_a.T 
    print("Matriz A: \n",matriz_a)
    print("Transpuesta: \n",transpuesta)   


ejercicio1()
ejercicio2()
ejercicio3()
ejercicio4()
ejercicio5()



[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matriz A: 
 [[6 7 4]
 [9 8 2]
 [8 9 3]]
Matriz B: 
 [[ 1  1 10]
 [ 1  1 10]
 [ 0  7  8]]
Suma: 
 [[ 7  8 14]
 [10  9 12]
 [ 8 16 11]]
Matriz A: 
 [[5 5 2]
 [2 5 1]
 [0 1 4]]
Escalar:  3
Multiplicacion: 
 [[15 15  6]
 [ 6 15  3]
 [ 0  3 12]]
Matriz A: 
 [[4 8]
 [4 3]]
Determinante:  -19.999999999999996
Matriz A: 
 [[1 8]
 [3 7]
 [9 2]]
Transpuesta: 
 [[1 3 9]
 [8 7 2]]


Borrar una fila específica de una matriz

Descripción:
Crea una matriz de tamaño 4×4 con números enteros aleatorios entre 0 y 9. Luego, elimina la segunda fila y muestra la matriz resultante.

In [4]:
def borrar_fila():
    matriz=np.random.randint(0,10,(4,4))
    eliminar_fila=np.delete(matriz,1,axis=0)
    print("Matriz original: \n",matriz)
    print("Matriz sin la fila 1: \n",eliminar_fila)

borrar_fila()

Matriz original: 
 [[7 2 0 0]
 [2 8 5 5]
 [3 1 9 9]
 [8 0 6 2]]
Matriz sin la fila 1: 
 [[7 2 0 0]
 [3 1 9 9]
 [8 0 6 2]]


Producto de dos matrices

Descripción:
Crea dos matrices de tamaño 3×3 con números enteros aleatorios entre 1 y 5. Realiza el producto de las dos matrices y muestra el resultado.

In [5]:
def producto_punto():
    matriz_a=np.random.randint(0,6,(3,3))
    matriz_b=np.random.randint(0,6,(3,3))
    producto_punto=np.dot(matriz_a,matriz_b)
    prod = matriz_a@matriz_b
    print("Matriz A: \n",matriz_a)
    print("Matriz B: \n",matriz_b)
    print("Producto punto: \n",producto_punto,"\n",prod)
    
producto_punto()

Matriz A: 
 [[5 0 2]
 [5 0 3]
 [1 1 1]]
Matriz B: 
 [[5 0 0]
 [4 2 0]
 [4 2 0]]
Producto punto: 
 [[33  4  0]
 [37  6  0]
 [13  4  0]] 
 [[33  4  0]
 [37  6  0]
 [13  4  0]]


 Determinar si una matriz es simétrica

Descripción:
Crea una matriz cuadrada de tamaño 3×3 con números enteros aleatorios entre 1 y 10. Determina si la matriz es simétrica y muestra el resultado.

Nota: Una matriz es simétrica si es igual a su transpuesta.

In [49]:
def es_simetrica():
    matriz=np.random.randint(0,11,(3,3))
    es_simetrica = (matriz == matriz.T).all()
    print("Matriz: \n",matriz)
    print("Es simetrica: ",es_simetrica)
    simetrica= np.array_equal(matriz, matriz.T)
    print("Es simetrica: ",simetrica)
    
es_simetrica()

Matriz: 
 [[9 3 1]
 [8 2 8]
 [4 8 0]]
Es simetrica:  False
Es simetrica:  False


Suma de los elementos de la diagonal principal y secundaria

Descripción:
Crea una matriz cuadrada de tamaño 4×4 con números enteros aleatorios entre 1 y 20. Calcula la suma de los elementos de su diagonal principal y su diagonal secundaria.

In [24]:
def sumnadiag():
    matriz=np.random.randint(1,21,(4,4))
    suma_diagonal_ppal = np.trace(matriz)
    suma_diagonal_sec = np.trace(matriz[:,::-1])
    diag_sec= np.fliplr(matriz).diagonal().sum()
    diag_ppal= matriz.diagonal().sum()
    diagsec2=np.trace(np.fliplr(matriz))
    print("Matriz: \n",matriz)
    print("Suma diagonal principal: ",suma_diagonal_ppal)
    print("Suma diagonal secundaria: ",suma_diagonal_sec)
    print("Suma diagonal principal: ",diag_ppal)
    print("Suma diagonal secundaria: ",diag_sec)
    print("Suma diagonal secundaria: ",diagsec2)
    
    
sumnadiag()
    
    

Matriz: 
 [[15 20 19  1]
 [20 15  1 17]
 [ 5  5 13 14]
 [ 8 15 18 15]]
Suma diagonal principal:  58
Suma diagonal secundaria:  15
Suma diagonal principal:  58
Suma diagonal secundaria:  15
Suma diagonal secundaria:  15


Encontrar la fila con mayor suma

Descripción:
Crea una matriz de tamaño 5×3 con números enteros aleatorios entre 0 y 15. Calcula la suma de los elementos de cada fila e identifica cuál fila tiene la mayor suma. Muestra la fila y su suma.

In [27]:
def mayor_suma():
    matriz= np.random.randint(0,16,(5,3))
    suma_filas = matriz.sum(axis=1)
    fila_max= np.argmax(suma_filas)
    print("Matriz: \n",matriz)
    print("Suma de las filas: ",suma_filas)
    print("Fila con mayor sumapor indice: ",fila_max)
    print(f"Fila con mayor suma : {fila_max+1} (suma: {suma_filas[fila_max]})")
    
mayor_suma()

Matriz: 
 [[ 2  7 11]
 [ 9 15  7]
 [10 13  2]
 [ 3 12 13]
 [ 0  6 11]]
Suma de las filas:  [20 31 25 28 17]
Fila con mayor sumapor indice:  1
Fila con mayor suma : 2 (suma: 31)


Descomposición L*U

Descripción:
Crea una matriz cuadrada 3×3 con números enteros aleatorios entre 1 y 10. Realiza su descomposición LU utilizando la biblioteca scipy.linalg. Muestra las matrices L y U resultantes.

In [31]:
import numpy as np
from scipy.linalg import lu
from scipy.sparse import random as sparse_random

def lu_f():
    matriz = np.random.randint(0,11,(6,6))
    P,L,U = lu(matriz)
    print("Matriz: \n",matriz)
    print("P: \n",P)
    print("L: \n",L)
    print("U: \n",U)
    
lu_f()        

Matriz: 
 [[ 1  5  4  4  1  6]
 [ 3  5  2  2  9  4]
 [ 5  7  0  1  7 10]
 [ 8  4 10  9  2  1]
 [ 4  2  7  8  6  5]
 [ 7  9  5  4  1  8]]
P: 
 [[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]]
L: 
 [[ 1.          0.          0.          0.          0.          0.        ]
 [ 0.875       1.          0.          0.          0.          0.        ]
 [ 0.125       0.81818182  1.          0.          0.          0.        ]
 [ 0.625       0.81818182 -0.546875    1.          0.          0.        ]
 [ 0.375       0.63636364  0.109375    0.23206751  1.          0.        ]
 [ 0.5         0.          0.34375     0.76793249 -0.13398295  1.        ]]
U: 
 [[ 8.          4.         10.          9.          2.          1.        ]
 [ 0.          5.5        -3.75       -3.875      -0.75        7.125     ]
 [ 0.          0.          5.81818182  6.04545455  1.36363636  0.04545455]
 [ 0.          0.          0.          1.8515

Ejercicio 2: Encontrar los autovalores y autovectores

Descripción:
Crea una matriz cuadrada 4×4 con números enteros aleatorios entre 1 y 5. Calcula los autovalores y autovectores de la matriz utilizando np.linalg.eig

Ejercicio 3: Resolver un sistema de ecuaciones lineales

Descripción:
Dado un sistema de ecuaciones representado por la matriz A (coeficientes) de tamaño 3×3 y un vector bb (términos independientes) de tamaño 3, resuelve el sistema A⋅x=b utilizando np.linalg.solve.

Ejercicio 4: Multiplicar matrices dispersas

Descripción:
Crea dos matrices dispersas 5×5 (con la mayoría de elementos siendo ceros) utilizando scipy.sparse.random. Convierte las matrices dispersas a formato denso y realiza su producto utilizando np.dot. Muestra las matrices iniciales y el resultado.

Ejercicio 5: Operaciones con la inversa de una matriz

Descripción:
Crea una matriz cuadrada invertible 3×3 con números aleatorios entre 1 y 10. Calcula su inversa utilizando np.linalg.inv, verifica que A⋅A−1=I (matriz identidad), y muestra el resultado.

In [51]:
def ejercicio2():
    matriz= np.random.randint(0,6,(4,4))
    autovalores,autovectores = np.linalg.eig(matriz)
    print("Matriz: \n",matriz)
    print("Autovalores: \n",autovalores)
    print("Autovectores: \n",autovectores)
    
def ejercicio3():
    A = np.random.randint(-100,101,(3,3))
    b = np.random.randint(-100,101,3)
    x = np.linalg.solve(A,b)
    print("Matriz A: \n",A)
    print("Vector b: \n",b)
    print("Solucion x: \n",x)
    
def ejercicio4():
    s_m1=sparse_random(5,5,density=0.2, format='coo', random_state=42).toarray()
    s_m2=sparse_random(5,5,density=0.2, format='coo', random_state=24).toarray()
    priducto_punto=s_m1@s_m2
    print("Matriz 1: \n",s_m1)
    print("Matriz 2: \n",s_m2)
    print("Producto punto: \n",priducto_punto)
    
def ejercicio5():
    matriz=np.random.randint(1,11,(3,3))
    while np.linalg.det(matriz)==0:
        matriz=np.random.randint(1,11,(3,3))
        
    inversa = np.linalg.inv(matriz)
    identidad = np.dot(matriz,inversa)
    print("Matriz: \n",matriz)
    print("Inversa: \n",inversa)
    print("Identidad: \n",identidad)
    
ejercicio2()
ejercicio3()
ejercicio4()
ejercicio5()


Matriz: 
 [[5 5 2 3]
 [0 1 4 1]
 [5 5 5 5]
 [4 3 1 4]]
Autovalores: 
 [13.02466777+0.j          0.9244923 +1.47771889j  0.9244923 -1.47771889j
  0.12634763+0.j        ]
Autovectores: 
 [[-0.49730706+0.j          0.33040729+0.47018863j  0.33040729-0.47018863j
  -0.71287662+0.j        ]
 [-0.27348913+0.j         -0.59714593+0.j         -0.59714593-0.j
   0.56995244+0.j        ]
 [-0.72425696+0.j         -0.08090782-0.12192332j -0.08090782+0.12192332j
  -0.21183715+0.j        ]
 [-0.39158811+0.j          0.36872041-0.39472055j  0.36872041+0.39472055j
   0.3494083 +0.j        ]]
Matriz A: 
 [[ 54 -99  24]
 [ -1 -70  26]
 [ 98  81  -4]]
Vector b: 
 [ 56 -14  51]
Solucion x: 
 [ 0.90284613 -0.56234422 -2.01774035]
Matriz 1: 
 [[0.43194502 0.         0.         0.         0.        ]
 [0.         0.         0.         0.30424224 0.        ]
 [0.         0.61185289 0.         0.         0.        ]
 [0.         0.52475643 0.         0.         0.        ]
 [0.         0.         0.         0.2

## Ejercicio 1: Optimización de recursos en una fábrica

Una fábrica produce 3 tipos de productos (A, B y C) utilizando 3 recursos (X, Y y Z). La cantidad de recursos necesarios por cada unidad de producto es:

M=[2,1,3,

   1,2,1,

   3,1,2]


El vector de producción semanal actual de la fábrica es:

P=[50,
30,
40]

​

Calcula cuántas unidades de cada recurso se consumen semanalmente.

## ejercicio 2 Análisis de redes sociales

En una red social, hay una matriz de adyacencia que representa las interacciones entre usuarios. Por ejemplo:

A=[0,1,0,1,

1,0,1,0

0,1,0,1,

1,0,1,0]

​

Aquí, un valor 1 indica una interacción directa entre dos usuarios.

    Calcula el grado de conexión de cada usuario (suma de cada fila).
    Determina si el grafo es simétrico, es decir, si la interacción es bidireccional.

## Ejercicio 3: Predicción de ventas en una tienda

Una tienda tiene tres productos: P1, P2, y P3, que son vendidos en dos ciudades: C1 y C2. Las ventas actuales están representadas en la matriz:

V=[200, 150,

300, 400,

250, 300]

​

Donde las filas representan productos y las columnas representan ciudades.

    Supón que las ventas aumentarán un 10% en C1 y un 20% en C2. Calcula la nueva matriz de ventas.
    Determina el producto más vendido en cada ciudad.

## Ejercicio 4: Análisis de imágenes en blanco y negro

En procesamiento de imágenes, las imágenes se representan como matrices de píxeles. Supongamos que tienes la siguiente matriz de intensidad de una imagen en escala de grises:

I=[0, 50, 100, 

150, 200, 255,

255, 200, 100]

​

    Aplica un filtro para incrementar la intensidad de cada píxel en un 10%, sin que ningún valor supere 255.
    Calcula el promedio de intensidad de toda la imagen. np.clip() para limitar valores

## Ejercicio 5: Pronóstico meteorológico

Un modelo simple para predecir la temperatura diaria en 3 ciudades durante 5 días genera la siguiente matriz:

T=[30, 32, 31, 33, 34,

25, 26, 27, 28, 29, 

20, 22, 21, 23, 24]


Cada fila representa una ciudad y cada columna un día.

    Calcula la temperatura promedio para cada ciudad durante los 5 días.
    Determina el día más caluroso en general.

In [53]:
def ejercicio1():
    M= np.array([
        [2,1,3],
        [1,2,1],
        [3,1,2]
    ])
    p=np.array([50,30,40])
    
    recursos_consumidos= M@p
    print("Recursos consumidos: ",recursos_consumidos)
    
ejercicio1()

Recursos consumidos:  [250 150 260]


In [54]:
def ejercicio2():
    A= np.array([
        [0,1,0,1],
        [1,0,1,0],
        [0,1,0,1],
        [1,0,1,0]])
    
    grados = np.sum(A,axis=1)
    print("Grado de conexion de cada usuario: ",grados)
    es_simetrico = np.array_equal(A, A.T)
    print("Es simetrico: ",es_simetrico)
    
ejercicio2()
    

Grado de conexion de cada usuario:  [2 2 2 2]
Es simetrico:  True


In [55]:
def ejercicio3():
    V=np.array([
        [200,150],
        [300,400],
        [250,300]
    ])
    
    incrementeC1= 0.1
    incrementeC2= 0.2
    
    nueva_Matriz=V*np.array([1+incrementeC1,1+incrementeC2])
    print("Nueva matriz: \n",nueva_Matriz)  
    
    producto_mas_vendido = np.argmax(nueva_Matriz,axis=0)
    print("Producto mas vendido: ",producto_mas_vendido)
    
ejercicio3()
    

Nueva matriz: 
 [[220. 180.]
 [330. 480.]
 [275. 360.]]
Producto mas vendido:  [1 1]


In [57]:
def ejercicio4():
    I=np.array([
        [0,50,100],
        [150,200,255],
        [255,200,100],
    ])
    filtro= I*1.10
    filtro = np.clip(filtro,0,255)
    print("Filtro: \n",filtro)
    
    promedio_intensidad = round(np.mean(I),2)
    print("Promedio de intensidad: ",promedio_intensidad)   
    
ejercicio4()
    

Filtro: 
 [[  0.  55. 110.]
 [165. 220. 255.]
 [255. 220. 110.]]
Promedio de intensidad:  145.56


In [ ]:
import numpy as np
def ejercicio5():
    T = np.array([
        [30,32,31,33,34],
        [25,26,40,28,29],
        [20,22,21,50,24]
    ])
    prom = np.mean(T)
    print("Promedio de temperatura: ",prom)
    prom_ciudad = np.mean(T,axis=1)
    print("Promedio de temperatura por ciudad: ",prom_ciudad)
    prom_dia = np.mean(T,axis=0)
    print("Promedio de temperatura por dia: ",prom_dia)
    diamax= np.argmax(T)
    print("Dia mas caluroso: ",diamax+1)
    diamax_fila, diamax_columna = divmod(diamax, T.shape[1])
    print(f"el dia mas coluroso fue el dia {diamax_columna+1} con una temperatura de {T[diamax_fila,diamax_columna]}")
    
    
    
ejercicio5()
    

Promedio de temperatura:  29.666666666666668
Promedio de temperatura por ciudad:  [32.  29.6 27.4]
Promedio de temperatura por dia:  [25.         26.66666667 30.66666667 37.         29.        ]
Dia mas caluroso:  1
el dia mas coluroso fue el dia 1 con una temperatura de 30


Composición porcentual de compuestos

Dada la matriz de masas molares de los elementos en un compuesto químico: (3x3 con rangos de 0.00 hasta 60)
Donde las filas representan los compuestos (CH₄, H₂O, NaCl) y las columnas representan los elementos (C, H, O, Cl). Calcula la composición porcentual de cada elemento en cada compuesto.(trnaspuesta de la matriz / sumatoria  de cada elemento)por cien

In [23]:
M = np.random.uniform(0.00,60.00,(3,4))
print(M)

[[46.91514269 43.43682003 38.09539187 16.99016668]
 [18.45217342 17.28384738  6.79363559 54.25378715]
 [36.55275813 14.75640705 57.67837338 39.442835  ]]


In [25]:
porcentaje =(M.T/np.sum(M,axis=1))*100
print("composicion porcentual: \n",porcentaje)

composicion porcentual: 
 [[32.25793611 19.06542354 24.6261983 ]
 [29.86630936 17.85826868  9.94163573]
 [26.19364765  7.01941917 38.85887504]
 [11.68210688 56.05688861 26.57329093]]


Ejercicio 1: Calcular la cantidad de producto formado en una reacción química

Enunciado:
En la reacción 2H2 + 02 ​→ 2H20 , se tienen 5 moles de H2​ y 3 moles de O2​. Usando matrices, determina cuántos moles de H20 se pueden formar, y verifica si sobra alguno de los reactivos.

FORMULAS
CANTIDAD DE PRODUCTO FORMADO = MIN(REACTIVO DISPONIBLE/COEFICENTE ESTEQUIOMETRICO)* COEFICEINTE DE PRODUCTO



In [34]:
import numpy as np
coeficeintes= np.array([2,1,2])
reactivos = np.array([5,3])

print(coeficeintes[2])

MF= min(reactivos/coeficeintes[:2])*coeficeintes[2]
print("Maximo de producto final: ",MF)
sobrantes = reactivos - (MF/ coeficeintes[2])*coeficeintes[:2]
print("Sobrantes: ",sobrantes)

2
Maximo de producto final:  5.0
Sobrantes:  [0.  0.5]


Balance de cargas en una solución iónica

Enunciado:
En una solución se tienen los siguientes iones:

    Na+ con concentración 0.10M.
    Cl− con concentración 0.08M.
    SO24−​ con concentración 0.04M.

Determina si la solución es eléctricamente neutra.

Fórmula a usar:

    Carga total=∑(concentracioˊn del ion×valencia)
    Si Carga total=0 la solución es neutra.

In [36]:
iones = np.array([
    [0.10,+1],
                 [0.08, -1],
                 [0.04, -2]
                 ])

cargatotal= np.sum(iones[:,0]*iones[:,1])
print("Carga total: ",cargatotal)
if cargatotal==0:
    print("La molecula es neutra")

Carga total:  -0.06


Ejercicio 2: Calcular el pH de una solución con varios ácidos

Enunciado:
Se mezclan dos ácidos en una solución:

    HCl con concentración 0.05M, que libera 1 ion H+ por molécula.
    H2SO4​ con concentración 0.02M, que libera 2 iones H+ por molécula.

Calcula el pH total de la solución, teniendo en cuenta la contribución de cada ácido.

formulas 
concentracion total de  H+ = sumatoria(concentracion de acifdo * numero de H+)

ph= -log10(concentracion total de  H+)

In [37]:
acidos =np.array([
    [0.05, 1], #acido clorhidrico
    [0.02, 2] # acido sulfurico
])  
H_total = np.sum(acidos[:,0]*acidos[:,1])
print("H total: ",H_total)
ph= -np.log10(H_total)
print("ph: ",ph)    

H total:  0.09
ph:  1.0457574905606752


Ejercicio: Determinar la estequiometría de una reacción química usando álgebra matricial

Enunciado:
Considera la reacción química genérica:

aA+bB→cC+dD


donde los compuestos son:

    A:CH4
    B:O2
    C:CO2
    D:H2O

Encuentra los coeficientes estequiométricos a,b,c,d resolviendo el sistema de ecuaciones generado por el balance de átomos de carbono (C), hidrógeno (H) y oxígeno (O).

Fórmulas a usar:

    Representa la reacción como un sistema lineal en forma matricial:

A⋅x=b

donde:

A = matriz randon de 3x4 rangos de -4 a 4

x = matriz a,b,c,d 4*1

b= matirz de ceros 3*1

In [47]:
A = np.random.randint(-4,5,(3,4))
b= np.zeros(3)
b

array([0., 0., 0.])

In [ ]:
A_aug = np.vstack([A,[1,0,0,0]])
b_aug = np.append(b,[1]) 
solucion = np.linalg.lstsq(A_aug,b_aug,rcond=None)[0] 
print("Solucion: ",solucion)
coeficientes = (solucion/np.min(np.abs(solucion[solucion > 0]))).astype(int)
print("Coeficientes: ",coeficientes)



Solucion:  [ 1.         -0.25581395 -0.1627907  -0.97674419]
Coeficientes:  [1 0 0 0]
